### ISSUE TITLE
[1.10.2] Crash on load 

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [Lordmau5/FFS#10]
**2.0.3-b11**:

**12.18.3.2281**:

**Client or Server?**:
- [ ] Client
- [X] Server

Hello, I am experiencing a crash on load after attaching a RF Tools Weak Powercube to a Fancy Fluid Storage Metaphaser.

https://pastebin.com/fqU4EBT6

**Comment by gigabit101** [comment]
this looks like it was a miss match in RF api's this will no longer happen in 1.12 as RF is its own jar
