### ISSUE TITLE
Tanks not "remembering" the correct amount of fluid stored

### ISSUE THREAD

**Issue by p4di** [Lordmau5/FFS#11]
**FancyFluidStorage Version**: Fancy Fluid Storage-1.10.2-2.0.3-b11

**MinecraftForge Version**: forge 1.10.2-12.18.3.2422

**Client or Server?**: Client, offline

**What happens / happened?**: Whenever I leave and then come back in the dimension or restart the game, my fluid tanks get filled up entirely with whatever fluid is im them.

**Comment by gigabit101** [comment]
fixed in 1.12+ 1.10 is not supported
