### ISSUE TITLE
Issue with quantities of fluid in tanks

### ISSUE THREAD

**Issue by Jack-of-a-few-trades** [Lordmau5/FFS#12]
**FancyFluidStorage Version**: 2.0.3

**MinecraftForge Version**: 12.18.3.1285

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

**What happens / happened?**: Tanks inaccurately remembering fluid amounts upon world loading. Tanks that had just a little fluid in them will suddenly be completely full when I reopen my world. 

**How can we reproduce it?**: I'm not sure.

**Comment by Lordmau5** [comment]
Over a year late to this issue due to the mod being maintained by someone else.

This should be fixed in v2.2.2 though.
