### ISSUE TITLE
Fancy Fluids Storage Constant Crash

### ISSUE THREAD

**Issue by SirTwsted** [Lordmau5/FFS#14]
**FancyFluidStorage Version**:
1.12-2.1.3.jar
**MinecraftForge Version**:
1.12.2
**Client or Server?**:
- [ X] Client
- [ O] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://pastebin.com/iqnURZRp

**What happens / happened?**:
Game keeps crashing, while im logging in the world just about to play.

**How can we reproduce it?**:
Just log in MC and wait, then crash happens.

**Comment by Lordmau5** [comment]
I'm over a year late to this because it was maintained by Gigabit.

I'm not sure how relevant this issue still is, but v2.2.1 changed how the config is being handled, so this issue shouldn't happen anymore.
