### ISSUE TITLE
No Bucket extraction

### ISSUE THREAD

**Issue by InvicTech** [Lordmau5/FFS#17]
**FancyFluidStorage Version**:
Fancy Fluid Storage-1.12-2.1.3.jar

**MinecraftForge Version**:
forge-14.21.4.2725

**Client or Server?**:
- [*] Client
- [*] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://pastebin.com/xLNU6yYW
It starts looping this Error-Msg as soon as I place down the valve and stops as soon as I activate the tank

**What happens / happened?**:
Storing Fluids works as normal, however the fluids can't be extracted with a bucket by right-clicking. When looking at the tank, it doesn't show the amount of fluid stored, just the material used (WAILA just shows glass, stone, ... but no information about the tank. 

**How can we reproduce it?**:
Overlay-Render is turned off in config, might have something to do with it.

**Modpack-Name**:
InvicPackReloaded (Version 5.1)
[https://www.curseforge.com/minecraft/modpacks/invicpackreloaded](url)

**Pictures**:
![2018-07-17_16 52 22](https://user-images.githubusercontent.com/20909194/42825254-e4f5f2f0-89e1-11e8-9b7b-ed781bdf99cf.png)
No Tank-Info, No bucket extraction

![2018-07-17_16 54 02](https://user-images.githubusercontent.com/20909194/42825335-1649af2c-89e2-11e8-8276-71ee73f7fc13.png)
Right-Clicking Opens Tank-UI, ...

![2018-07-17_16 54 04](https://user-images.githubusercontent.com/20909194/42825395-358c298c-89e2-11e8-94f3-6be50329fca1.png)
... however it only shows the amount of fluid stored when hovering over certain spots.

![2018-07-17_17 03 28](https://user-images.githubusercontent.com/20909194/42825918-669485b4-89e3-11e8-8be8-589eeb6385dd.png)
Animation is shown when right-clicking (Same on Server and in Singleplayer)

**Comment by Lordmau5** [comment]
Half a year late because Gigabit was kind enough to maintain it.

No idea how relevant this issue still is, but it should be fixed in the newest version (v2.2.1 as of writing this comment)

I'll leave it open for a bit, maybe you get a chance to try it again
