### ISSUE TITLE
Configurable Block Whitelist

### ISSUE THREAD

**Issue by pyure** [Lordmau5/FFS#23]
Hiya Lordmau5, we're excited that you've resumed development on this mod!

Request: Please allow users to specify a block whitelist (default: anything goes) so that players can only generate valid FFS structures with specific blocks.

(I've reviewed prior issues to ensure I'm not requesting something already rejected)

**Comment by Lordmau5** [comment]
Hey there - for whatever reason GitHub has made me unwatch this repository and I never got any notification about the new issues, so I'm really sorry that I respond to this almost a month too late.

A white- or blacklist sounds like an interesting concept, should be doable somehow.

Do you have any suggestions as to how it should function?
Have it be a list of block IDs with wildcard support?

**Comment by pyure** [comment]
No worries at all.

Wildcard support is a bonus, but not even really critical.  I'd probably just do something that looks like CT brackethandlers, or any other block syntax you like, in any array format you like (linefeed separated, comma delimited, json arrays, whatever floats your boat)

**Comment by pyure** [comment]
Friendly reminder that we care :)  Not a rush of any sort whatsoever, but letting you know we're using and enjoying the mod and look forward to tweaking the wall restrictions if possible!

**Comment by Lordmau5** [comment]
Hey, sorry, I got caught up with IRL stuff over the past 2 weeks and haven't gotten time to look into it much... I should be able to look into it from Sunday onwards though, maybe able to push a first "draft" of this that you can work with potentially

Once again, really sorry for this :/

**Comment by pyure** [comment]
You rock, thanks kindly sir.  Seriously, don't rush, just didn't want you to think we didn't care ;)

**Comment by Lordmau5** [comment]
Alright, I got a white-/blacklist implemented now that works by adding specific registry names of blocks, so for example `minecraft:glass` would block all Glass from being used in a tank.

Would be cool if you could grab the build from here and test it out before I push it to CurseForge :D

https://jenkins.lord.moe/job/Fancy%20Fluid%20Storage/3/

**Comment by pyure** [comment]
Sweet!  If you can tolerate a 24-36 hour wait I should definitely be able to give you feedback.

**Comment by pyure** [comment]
Here you go LordMau5 :)

* Mod loads fine!
* Block whitelist works as advertised
* Could not figure out a way to specify meta-data.  Tried gregtech:metal_casing@1, gregtech:metal_casing:1
* Having an option called "Invert Whitelist" when "Blacklist" is actually the default state feels odd.  Either the default should change, or the name of the option.

**Comment by Lordmau5** [comment]
- Glad to hear it didn't break anything :D
- See 1
- I'll make sure to see how I can best implement this. Shouldn't be too hard to do though, and I'll probably go with the `<modid>:<block>@<metadata>` syntax purely because I don't trust certain mods using some weird combination of `<modid>:<block>:<more_block_info>`
- Yeah, I'll be renaming it to "Blacklist" instead, makes much more sense

I'll respond a 2nd time when I got some changes up for another test :)

**Comment by Lordmau5** [comment]
Alright, build finished just now - It worked during my short test period, but you're the one to decide if it's working or not ;)

https://jenkins.lord.moe/job/Fancy%20Fluid%20Storage/4/

**Comment by pyure** [comment]
Goodness that was quick!

* Blacklist works as expected
* Inverted blacklist into whitelist works as expected 
* Metadata works as expected, but see below
* Not specifying metadata functions as wildcard (all meta) rather than @0.  This is probably fine, just wanted you to be aware. (Saves us the trouble of requiring a wildcard symbol, and we can specify @0 if we want to)
