### ISSUE TITLE
Crash: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Sewef** [Lordmau5/FFS#26]
**FancyFluidStorage Version**: 2.1.3

**MinecraftForge Version**: 2837

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://pastebin.com/s1VtGJVf

**What happens / happened?**:
Client crash happened on server.
I made a tank, put some Essence Of Knowledge (from Thermal Foundation), then right clicked the Valve. The game crashed.

**How can we reproduce it?**:

**Comment by Lordmau5** [comment]
The latest release build requires [Reborn Core](https://minecraft.curseforge.com/projects/reborncore) and is also lacking behind on features (and even bug fixes).

I've just changed the latest Alpha build into a Release build, so make sure to update to 2.2.4 :)

I'll leave the issue open for now in case you still have some issues with that version.

**Comment by Sewef** [comment]
I'm using Steve's Cart Reborn so that's not the problem.
I'll test this asap :)

**Comment by Lordmau5** [comment]
Wow, my bad - I meant to say that anything **below Version 2.2 requires RebornCore**.
When I was writing that first response the release build at the time was still 2.1.3 and the other ones were set to be an Alpha, so I'm sorry for the confusion.

The RebornCore dependency was removed in 2.2 onwards :)

**Comment by Lordmau5** [comment]
I'm just gonna go ahead and close this, assuming that it has been resolved.
In case there are still some issues, please open up a new one :)
