### ISSUE TITLE
Fluiduct input pipes disconnect when chunk unloaded

### ISSUE THREAD

**Issue by Chintagious** [Lordmau5/FFS#27]
**FancyFluidStorage Version**: 2.2.4

**MinecraftForge Version**: 14.23.5.2836

**Client or Server?**:
- [ ] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/A

**What happens / happened?**: I am playing the modpack FTB Ultimate Reloaded v1.7.1. I have a tank with 2 valves, one input and one output, both connected with fluiducts (Thermal Dynamics v2.5.4.18). When I disconnect and come back, I see that the tank is "turned off" and the input pipe is no longer connected with the tank.

**How can we reproduce it?**: 
1. Install the mod Thermal Dynamics v2.5.4.18 (or use the modpack FTB Ultimate Reloaded v1.7.1)
1. Make any simple tank (I used Vibrant Quartz Glass, Spruce Wood Planks, and Stone Bricks) 
1. Connect one valve with Fluiduct and a servo for extraction
1. Connect another valve with another fluiduct for input 
1. Right click the valve to turn the tank on
1. Log out, then log back in (or have the chunk unload and reload)

**Comment by Chintagious** [comment]
Looks like this doesn't happen every time.. Super strange. Occasionally it happens multiple times in a row, and then sometimes it doesn't happen for a bit. Not sure what's up.

**Comment by Lordmau5** [comment]
Gonna close this up as the mod is now on 1.16.3 and 1.12 is not supported anymore
