### ISSUE TITLE
[1.10.2] Client crashes when right clicking with negative paper thing

### ISSUE THREAD

**Issue by DeadSix27** [Lordmau5/FFS#3]
this crash seems to be caused by FFS but it happends when using just CnB stuff. I do not even have a FFS built yet.

EDIT: I disabled this mod and it does not crash anymore, so its not caused by CnB itself.

FFS: `Fancy Fluid Storage-1.10.2-2.0.1-b8.jar`
Forge: `forge-1.10.2-12.18.3.2202`

**Client or Server?**:
- [X] Client (crashes)
- [X] Server (does not crash, just an error)

Client stacktrace: http://pastebin.com/GaqjYpFv
Server stacktrace: http://pastebin.com/RNQS7dSd

### Description:

Right clicking a chiseled block with the red negative paper thing makes my client crash and the server throw an error (server does not crash)

**Comment by Lordmau5** [comment]
Ah. It seems like the world object for the event is null at that moment, for whatever reason?

I can edit it on Github and trigger a new build.

I can't really do anything else up until the 17th/18th since I'm at AGDQ right now.

**Comment by DeadSix27** [comment]
@Lordmau5 its fine, ill keep it disabled until you properly release it (or clone and build it myself if i find the time)

**Comment by Lordmau5** [comment]
Don't close it you goofball! Urgh...

So it's up on Curseforge now.
Would you mind giving it a go?

https://minecraft.curseforge.com/projects/ffs-fancy-fluid-storage/files/2365528

**Comment by DeadSix27** [comment]
Seems to be fixed. No crash and no errors.

 (I only tried it in creative, I do not even know how the negative-paper thing of CnB works in survival lol.. right clicking does nothing there)

But ye no crash!
