### ISSUE TITLE
Servercrash

### ISSUE THREAD

**Issue by BedrockLegends** [Lordmau5/FFS#31]
**FancyFluidStorage Version**: 1.16.3-3.0.4

**MinecraftForge Version**: 34.1.25

**Client or Server?**:
- [ ] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
[crash-2020-10-22_22.37.26-server.txt](https://github.com/Lordmau5/FFS/files/5427200/crash-2020-10-22_22.37.26-server.txt)
**What happens / happened?**:

**How can we reproduce it?**:
Right Click on tank value cause the server to crash

**Comment by Lordmau5** [comment]
Ah, it seems I was using some convenient client-only function to format the blacklisted block's position in a chat message.

Fixed in v3.0.6 :)
