### ISSUE TITLE
ComputerCraft Support

### ISSUE THREAD

**Issue by jared-hess** [Lordmau5/FFS#32]
**FancyFluidStorage Version**: 2.2.5

**MinecraftForge Version**: 14.23.5.2846

Is computercraft support implemented in the 1.12 branch? Using "peripheral.getMethods()" for the side the tank computer is on only returns the default "getDocs()" and "getMetadata()" methods. Seems like a lot of the code relating to CC is commented out in the branch, but I'm not really familiar with the CC api so not sure what all is required there.
It's possible I'm just doing something wrong! Happy to provide any other info if it helps.

**Comment by Lordmau5** [comment]
1.12 is not supported anymore, though I did notice 1.16 has ComputerCraft and that might be a possibility to bring it back on there.

**Comment by Lordmau5** [comment]
Well, it's been a bit over 2 years and I can now say that ComputerCraft (or rather, CC:Tweaked) support is back for 1.19.2 in v3.3.6 of the mod :)
