### ISSUE TITLE
server crash on 1.16.5

### ISSUE THREAD

**Issue by Haxorouse** [Lordmau5/FFS#33]
**FancyFluidStorage Version**:3.1.0

**MinecraftForge Version**:1.16.5

**Client or Server?**:
- [ ] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:https://pastebin.com/TXHvXVQ9

**What happens / happened?**:upon flying(Elytra) into an area with large FFS tanks holding IE oil, the server would crash leaving the client fine. These tanks had been fine for a long time, the eventually started causing crashes, I think other tanks on the server didn't cause the same crash. we suspect it was caused by a data race in the chunk loading

**How can we reproduce it?**:

**Comment by Lordmau5** [comment]
Hmm unfortunately that crash report snippet doesn't mention anything FFS related so it's a bit tricky for me to track down :(

**Comment by Lordmau5** [comment]
If you do feel a bit adventurous and would like to test the mod on 1.16.5 again, I've just fixed a long-standing performance bug that brings in a ~60x performance boost for the tank search algorithm.

Having it look it's way through ~40k air blocks only takes around 35ms in my testing - a tank with ~4,500 air blocks took 2-5ms to build. It's very snappy and fast haha

https://www.curseforge.com/minecraft/mc-mods/ffs-fancy-fluid-storage/files/4351128
