### ISSUE TITLE
Fluids in Tanks cause Graphical Bugs with Certain Blocks & Entities

### ISSUE THREAD

**Issue by FocalFlare** [Lordmau5/FFS#34]
**DISCLAIMER** 
_I am using shaders and resource packs in the following screenshots. And while some of them may be the culprit of this issue, I've witnessed this even without any shaders or resource packs enabled way before I found out by hard that this mod was causing them. No hard/soft/vague crashes (because why would a graphical bug even cause a crash?), so I can't post a relevant log, although I can post one in case further action is needed._

_I wasn't able to find a single issue about this made on this mod, so I guess I'll insist on being the first._

_As always, solutions for this issue might work for everyone who's having this same issue but are 100% not guaranteed to work for those with even a slightly different issue. Regardless, I appreciate your input(s)!_

**Fancy Fluid Storage Version**
3.2.6 (Latest for 1.18.2)

**Minecraft Forge Version**
40.2.9

**Client or Server?**
- [x] Client
- [ ] Server
_No way for me to test this on a server, so I can only assume this is client-sided._

**Crash Report (via. [Paste.ee](https://paste.ee/))**
_No crashes occurred with the mod._

**Describe the bug**
_Whenever there's [any amount (mB) of] fluid inside a tank, entities and certain blocks will appear to render inside-out as if they have flipped normals. That and also some other graphical bugs. It's hard to thoroughly describe this bug with just text, so I'll provide some screenshots below._ 

**To Reproduce**
1. Find (or spawn) some entities/blocks.
2. Insert any fluid into the tank with entities and/or around.
3. ???
4. Profit (watch the blocks/entities render inside-out immediately when there's fluid added to the tank via the tank valve).

**Expected behavior**
_Fluid is added to an FFS tank without any graphical bugs._

**Screenshots**
No Fluid in Tank
![image](https://github.com/Lordmau5/FFS/assets/78162943/82c2b543-dedf-40ae-8ed6-f739477560d8)
![image](https://github.com/Lordmau5/FFS/assets/78162943/87cd664f-d848-4a0b-982d-fc2cd58fac95)
Fluid in Tank
![image](https://github.com/Lordmau5/FFS/assets/78162943/f2eae60b-d5ab-4ab2-a518-2aece8c1558b)
![image](https://github.com/Lordmau5/FFS/assets/78162943/5488ccf9-0fdd-4260-a21b-34b114123b73)
Other Entities, Player Armor Rendering, Water Rendering
![image](https://github.com/Lordmau5/FFS/assets/78162943/92f4e8da-409c-4b7f-bc6f-4f9172de87a8)

**Additional context**
_This doesn't just occur with only water or lava in a tank. I've also tested this with other (acceptable) fluids such as molten soulsteel from **Thermal Series**._

_This mod may or may not receive updates or support either for 1.18.2 or as a whole, so I won't keep any promises that this will be fixed. But hopefully, this can be looked at._

**Comment by Lordmau5** [comment]
I booted up the 1.18 development environment with just FFS and Little Logistics so I could try out that Steam Locomotive you have in your screenshots, but it looks fine...
![image](https://github.com/Lordmau5/FFS/assets/1345036/0fbb6ac3-9e64-4eb3-9c3a-e92d87c7a308)

This sounds like some mod incompatibility for sure, but without a list of mods I wouldn't know what it could be...

Would you perhaps be so kind as to make a copy of the modpack (or instance) that you have and remove mods 1-by-1 (or maybe in bulk) until the problem disappears?

As tested just now, Little Logistics still seems to work, so we have 1 mod we can test it with while removing all the other ones

I also wanna point out that I value this very detailed issue report a lot, thank you for that! 😄 

___

Actually, I asked some friends for help and they told me that one thing I've done incorrectly from 1.18 onwards was something in regards to the depth mask for rendering.

Could you try this version in the archive for 1.18.2 and see if that works for you? No need to remove the mods 1-by-1 for now 😉 

[Fancy Fluid Storage-1.18.2-3.2.7.zip](https://github.com/Lordmau5/FFS/files/12079154/Fancy.Fluid.Storage-1.18.2-3.2.7.zip)

**Comment by FocalFlare** [comment]
_Alright I'll try that out. I have too many mods to try and trial-and-error for, so it'll be tedious, but what I can do is send all the mods over as one archive file. As said, this happens with all entities and not just Little Logistics, despite the locomotives and the carts shown._

**Comment by Lordmau5** [comment]
A modpack in an archive would be very handy, that way I can look into it instead

Though, only if the issue still persists with that version I posted 😄

**Comment by FocalFlare** [comment]
_I don't play on any mod packs, but I can send the mods I left enabled here while I test out this version:_ _https://www.filesharing.com/download/KuZnb0E5NzJRaR5BD5Ii_

_Edit 71823: I tested the version you provided out and there are no graphical bugs present. However, I'll still wait for your input on this issue._ 👍🏾

**Comment by Lordmau5** [comment]
In that case we're done and it's fixed :)

I'll get new versions out for 1.18, 1.19 and also 1.20

Thank you for bringing this to my attention!
