### ISSUE TITLE
Client crash with Actually Additions drill in ExtraUtilities2 Deep Dark

### ISSUE THREAD

**Issue by dylandevalia** [Lordmau5/FFS#4]
**FancyFluidStorage Version**: 1.10.2-2.0.2-b9

**MinecraftForge Version**: 1.10.2

**Client or Server?**:
- [ x] Client
- [  ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://pastebin.com/sK7Q7pAh

**What happens / happened?**: Crashed client. I was breaking iron ore with my 3x3 drill from Actually Additions, holding shift to disable its 3x3 functionality. was not holding GRAVE for veinmine. Was in the ExtraUtilities2 Deep Dark (ID:-11325)

*You told me to post it here from discord :P*

**Comment by gigabit101** [comment]
Interesting crash lol

**Comment by gigabit101** [comment]
fixed in 1.12
