### ISSUE TITLE
Fluid Dupe

### ISSUE THREAD

**Issue by MrByryndyk** [Lordmau5/FFS#8]
**FancyFluidStorage Version**:
2.0.3

**MinecraftForge Version**:
12.18.3.2254

**Client or Server?**:
- [x] Client

**What happens / happened?**:
I play a single. I leave the game - I go back - the amount of liquid in the tank increases in two.
Checked with different liquids - all the same.

**Comment by gigabit101** [comment]
Ok so if there is more than one valve this happens

**Comment by gigabit101** [comment]
fixed in 1.12
